name: Publish
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0
      - name: Setup Node 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Build code
        run: npm run build
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
